### ISSUE TITLE
When trying to execute using examples got an error

### ISSUE THREAD

**Issue by alexkas1977** [BBVA/chaos-monkey-engine#10]
I install keeping your docker directory structure
/opt/chaosmonkey/src/(planners|attacks|storage)
python-2.7.14

api calls to list planners and attacks are working

plan.json
{
    "name": "Terminate random running instance",
    "attack": {
        "ref": "terminate_ec2_instance:TerminateEC2Instance",
        "args": {
            "filters": {
                "tag:chaos": "true"
            }
        }
    },
    "planner": {
        "args": {
            "min_time": "10:00",
            "max_time": "18:00",
            "times": 3
        },
    "ref": "simple_planner:SimplePlanner"
    }
}

[2018-04-06 08:40:36,130] ERROR in app: Exception on /api/1/plans/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/Flask_Cors-3.0.2-py2.7.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/chaosmonkey/api/plans_blueprint.py", line 91, in add_plan
    manager.execute_plan(name, planner_config, attack_config)
  File "/usr/local/lib/python2.7/site-packages/chaosmonkey/engine/cme_manager.py", line 169, in execute_plan
    planner_class = self._planners_store.get(planner_config.get("ref"))
  File "/usr/local/lib/python2.7/site-packages/chaosmonkey/modules/module_store.py", line 86, in get
    return self._ref_to_obj(ref)
  File "/usr/local/lib/python2.7/site-packages/chaosmonkey/modules/module_store.py", line 116, in _ref_to_obj
    raise TypeError('References must be strings')
TypeError: References must be strings

**Comment by gdiazlo** [comment]
We do not plan to support python2 but we'll accept PRs adding that support. I suppose the #12 is that PR but we need it to work before applying it.
